services:
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pizzeria
      MYSQL_USER: roberto
      MYSQL_PASSWORD: roberto.sesamo
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: